### ISSUE TITLE
Это что?

### ISSUE THREAD

**Issue by vdsimako** [instaHipsta282/harService#4]
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/15703327/72219741-4d64c580-355a-11ea-9e95-a1d77b3ab648.png">

**Comment by instaHipsta282** [comment]
DataSourceConfig убрал, с RabbitConfiguration что-то не так?

**Comment by vdsimako** [comment]
@instaHipsta282 то, что жато можно сделать с помощью autoconfigure  - зачем руками все прописывать, если умеет делать инструмент?

**Comment by instaHipsta282** [comment]
Убрал все, что управляется autoconfigure(connectionFactory, amqpAdmin, rabbitTemplate), оставил queue, exchange, binding
