### ISSUE TITLE
Какой процент покрытия тестами?

### ISSUE THREAD

**Issue by vdsimako** [instaHipsta282/harService#5]

**Comment by instaHipsta282** [comment]
@vdsimako 79%
![изображение](https://user-images.githubusercontent.com/45939689/72236766-35885280-35e9-11ea-9a91-576cc1ee020d.png)

**Comment by vdsimako** [comment]
@instaHipsta282  надо прикрутить jacoco plugin

**Comment by instaHipsta282** [comment]
Добавил плагин, покрытие на данный момент 75%. Сделал merge request.

**Comment by vdsimako** [comment]
![image](https://user-images.githubusercontent.com/15703327/72257692-4d79c980-361d-11ea-992f-cfbdfd663979.png)

тут ни разу не 75% - 50 вернее

**Comment by instaHipsta282** [comment]
@vdsimako  
![изображение](https://user-images.githubusercontent.com/45939689/72418874-bf245580-378c-11ea-9e4c-3109e3821d3d.png)
